"""
Generates a one-page markdown experiment report from engine results.
Used by pages/5_Report_Summary.py for display + download.
"""

from datetime import datetime


def generate_markdown_report(
    config: dict,
    stats_results: dict,     # StatsEngine.run_all()
    bayes_results: dict,     # BayesianEngine.run_all()
    decision_results: dict,  # DecisionEngine.run_all()
    data_info: dict,         # {"total": int, "control": int, "treatment": int, "days": int|None}
) -> str:
    conv = stats_results["conversion"]
    rev_test = stats_results["revenue"]
    power = stats_results["power"]
    bayes = bayes_results["result"]
    dec = decision_results["decision"]
    impact = decision_results["revenue_impact"]
    rr = decision_results["risk_reward"]
    scenarios = decision_results["scenarios"]

    duration = f"{data_info['days']} days" if data_info.get("days") else "n/a"

    has_revenue = bool(rev_test.control_mean or rev_test.treatment_mean)
    revenue_row = (
        f"| Revenue / user | ${rev_test.control_mean:.3f} | ${rev_test.treatment_mean:.3f} "
        f"| {rev_test.relative_lift_pct:+.2f}% rel. |"
    ) if has_revenue else ""
    welch_line = (
        f"- Welch's t-test (revenue/user): t = {rev_test.t_statistic:.3f}, "
        f"p = {rev_test.p_value:.4f}, Cohen's d = {rev_test.cohens_d:.4f}"
    ) if has_revenue else ""

    rationale_md = "\n".join(f"- {point}" for point in dec.rationale)
    scenarios_md = scenarios.to_markdown(index=False)

    return f"""# Experiment Report: {config['experiment_name']}

*Generated {datetime.now():%d %b %Y %H:%M}*

## Executive summary

**Recommendation: {dec.recommendation}** (confidence: {dec.confidence}, risk: {dec.risk_rating})

{rationale_md}

## Experiment design

| | |
|---|---|
| Hypothesis | {config.get('hypothesis', '–')} |
| Primary metric | {config.get('metric', 'conversion_rate')} |
| Variants | {config.get('control_label', 'Control')} vs {config.get('treatment_label', 'Treatment')} |
| Sample size | {data_info['control']:,} control / {data_info['treatment']:,} treatment |
| Duration | {duration} |
| Significance level | α = {conv.alpha} |

## Frequentist results

| Metric | Control | Treatment | Lift |
|---|---|---|---|
| Conversion rate | {conv.control_rate*100:.2f}% | {conv.treatment_rate*100:.2f}% | {conv.relative_lift_pct:+.2f}% rel. |
| 95% CI | [{conv.control_ci[0]*100:.2f}%, {conv.control_ci[1]*100:.2f}%] | [{conv.treatment_ci[0]*100:.2f}%, {conv.treatment_ci[1]*100:.2f}%] | |
{revenue_row}

- Two-proportion z-test: z = {conv.z_statistic:.3f}, p = {conv.p_value:.4f} – **{'significant' if conv.significant else 'not significant'}** at α = {conv.alpha}
{welch_line}
- Power: {power.achieved_power*100:.1f}% achieved for a {power.mde_relative_pct:.0f}% MDE (required n = {power.required_n_per_group:,}/group, current n = {power.current_n_per_group:,}/group)

## Bayesian results

Prior: Beta({bayes.prior_alpha:g}, {bayes.prior_beta:g})

| Metric | Value |
|---|---|
| P(treatment > control) | {bayes.prob_treatment_better*100:.1f}% |
| Expected relative uplift | {bayes.relative_uplift_pct:+.2f}% |
| Expected loss if shipping treatment | {bayes.expected_loss_treatment*100:.4f} pp |
| Expected loss if keeping control | {bayes.expected_loss_control*100:.4f} pp |
| Control 95% credible interval | [{bayes.control_credible_interval[0]*100:.2f}%, {bayes.control_credible_interval[1]*100:.2f}%] |
| Treatment 95% credible interval | [{bayes.treatment_credible_interval[0]*100:.2f}%, {bayes.treatment_credible_interval[1]*100:.2f}%] |

## Business impact

Assumptions: {impact.daily_visitors:,} daily visitors, {impact.traffic_split:.0%} of traffic affected, ${impact.revenue_per_conversion:,.2f} revenue per conversion.

| Metric | Value |
|---|---|
| Daily conversion lift | {impact.daily_conversion_lift:+.1f} conversions/day |
| Daily revenue lift | ${impact.daily_revenue_lift:+,.2f}/day |
| Annual revenue lift (point estimate) | ${impact.annual_revenue_lift:+,.0f} |
| Annual range (treatment CI) | ${impact.annual_revenue_lift_low:,.0f} to ${impact.annual_revenue_lift_high:,.0f} |
| EV of shipping vs status quo | ${rr.ev_ship_treatment:+,.2f}/day |

### Scenario analysis

{scenarios_md}

## Caveats

- Annualised figures extrapolate a short test window; seasonality and novelty effects may erode the lift.
- Revenue impact assumes the conversion lift is the only effect (no change in average order value).
- Scenario probabilities are illustrative weights, not posterior probabilities.

---
*Generated by the A/B Testing + Decision Analysis Dashboard.*
"""


# ── PDF report ────────────────────────────────────────────────────────────────

def _pdf_safe(text: str) -> str:
    """Replace unicode chars that reportlab's built-in fonts can't render."""
    replacements = {
        "≥": ">=", "≤": "<=", "–": "-", "–": "-", "·": "-",
        "→": "->", "−": "-", "α": "alpha", "β": "beta", "χ²": "chi-sq",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def generate_pdf_report(
    config: dict,
    stats_results: dict,
    bayes_results: dict,
    decision_results: dict,
    data_info: dict,
) -> bytes:
    """Builds a styled one-page(ish) PDF report and returns it as bytes
    for st.download_button."""
    from io import BytesIO
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )

    conv = stats_results["conversion"]
    rev_test = stats_results["revenue"]
    power = stats_results["power"]
    bayes = bayes_results["result"]
    dec = decision_results["decision"]
    impact = decision_results["revenue_impact"]
    rr = decision_results["risk_reward"]
    scenarios = decision_results["scenarios"]

    # palette echoes the dashboard (FT salmon)
    SLATE = colors.HexColor("#33302E")    # ink
    ACCENT = colors.HexColor("#990F3D")   # claret
    GREY = colors.HexColor("#7A7265")     # warm grey
    PAPER = colors.HexColor("#FFF1E5")    # salmon paper
    WHEAT = colors.HexColor("#F6E5D3")    # row stripe
    TAN = colors.HexColor("#D9C2A9")      # table grid
    REC_COLOURS = {
        "SHIP": colors.HexColor("#1F6E3C"),
        "DO NOT SHIP": colors.HexColor("#9E2B25"),
        "CONTINUE TESTING": colors.HexColor("#9A6B15"),
    }

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1x", parent=styles["Title"], fontSize=19, spaceAfter=2,
                        textColor=SLATE, alignment=0, fontName="Times-Bold")
    kicker = ParagraphStyle("kicker", parent=styles["Normal"], fontSize=8,
                            textColor=ACCENT, spaceAfter=4, fontName="Courier-Bold")
    h2 = ParagraphStyle("h2x", parent=styles["Heading2"], fontSize=12,
                        textColor=SLATE, spaceBefore=12, spaceAfter=4,
                        fontName="Times-Bold")
    body = ParagraphStyle("bodyx", parent=styles["Normal"], fontSize=9, leading=12)
    small = ParagraphStyle("smallx", parent=styles["Normal"], fontSize=7.5,
                           leading=10, textColor=GREY)
    rec_style = ParagraphStyle("recx", parent=styles["Normal"], fontSize=14,
                               textColor=colors.white, leading=18)

    def table_style(header_bg=ACCENT):
        return TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), header_bg),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#FFF1E5")),
            ("TEXTCOLOR", (0, 1), (-1, -1), SLATE),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, TAN),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, WHEAT]),
        ])

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"Experiment Report - {config['experiment_name']}",
    )

    def _salmon_page(canvas, doc_):
        canvas.saveState()
        canvas.setFillColor(PAPER)
        canvas.rect(0, 0, A4[0], A4[1], stroke=0, fill=1)
        canvas.restoreState()

    story = []

    # header
    story.append(Paragraph("EXPERIMENTATION - DECISION SCIENCE", kicker))
    story.append(Paragraph(_pdf_safe(f"Experiment Report: {config['experiment_name']}"), h1))
    story.append(Paragraph(f"Generated {datetime.now():%d %b %Y %H:%M}", small))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.8, color=ACCENT))
    story.append(Spacer(1, 8))

    # recommendation banner
    rec_tbl = Table(
        [[Paragraph(f"<b>Recommendation: {dec.recommendation}</b>", rec_style)],
         [Paragraph(f"Confidence: {dec.confidence} | Risk: {dec.risk_rating}",
                    ParagraphStyle("sub", parent=rec_style, fontSize=9))]],
        colWidths=[doc.width],
    )
    rec_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), REC_COLOURS.get(dec.recommendation, SLATE)),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 8),
    ]))
    story.append(rec_tbl)
    story.append(Spacer(1, 4))
    for point in dec.rationale:
        story.append(Paragraph(_pdf_safe(f"&bull; {point}"), body))

    # design
    story.append(Paragraph("Experiment design", h2))
    design_rows = [
        ["Hypothesis", _pdf_safe(config.get("hypothesis", "-"))],
        ["Variants", _pdf_safe(f"{config.get('control_label','Control')} vs {config.get('treatment_label','Treatment')}")],
        ["Sample size", f"{data_info['control']:,} control / {data_info['treatment']:,} treatment"],
        ["Duration", f"{data_info['days']} days" if data_info.get("days") else "n/a"],
        ["Significance level", f"alpha = {conv.alpha}"],
    ]
    t = Table([["Field", "Value"]] + design_rows, colWidths=[35 * mm, doc.width - 35 * mm])
    t.setStyle(table_style())
    story.append(t)

    # frequentist
    story.append(Paragraph("Frequentist results", h2))
    freq_rows = [
        ["Metric", "Control", "Treatment", "Lift"],
        ["Conversion rate", f"{conv.control_rate*100:.2f}%", f"{conv.treatment_rate*100:.2f}%",
         f"{conv.relative_lift_pct:+.2f}% rel."],
        ["95% CI", f"[{conv.control_ci[0]*100:.2f}%, {conv.control_ci[1]*100:.2f}%]",
         f"[{conv.treatment_ci[0]*100:.2f}%, {conv.treatment_ci[1]*100:.2f}%]", ""],
    ]
    if rev_test.control_mean or rev_test.treatment_mean:
        freq_rows.append(["Revenue / user", f"${rev_test.control_mean:.3f}",
                          f"${rev_test.treatment_mean:.3f}",
                          f"{rev_test.relative_lift_pct:+.2f}% rel."])
    t = Table(freq_rows, colWidths=[doc.width * w for w in (0.28, 0.27, 0.27, 0.18)])
    t.setStyle(table_style())
    story.append(t)
    story.append(Spacer(1, 3))
    welch_part = (
        f"Welch t-test (revenue/user): t = {rev_test.t_statistic:.3f}, p = {rev_test.p_value:.4f}, "
        f"Cohen's d = {rev_test.cohens_d:.4f}. "
        if (rev_test.control_mean or rev_test.treatment_mean) else ""
    )
    story.append(Paragraph(_pdf_safe(
        f"Two-proportion z-test: z = {conv.z_statistic:.3f}, p = {conv.p_value:.4f} "
        f"({'significant' if conv.significant else 'not significant'} at alpha = {conv.alpha}). "
        + welch_part +
        f"Power: {power.achieved_power*100:.1f}% for a {power.mde_relative_pct:.0f}% MDE "
        f"(required n = {power.required_n_per_group:,}/group)."), small))

    # bayesian
    story.append(Paragraph("Bayesian results", h2))
    bayes_rows = [
        ["Metric", "Value"],
        ["P(treatment > control)", f"{bayes.prob_treatment_better*100:.1f}%"],
        ["Expected relative uplift", f"{bayes.relative_uplift_pct:+.2f}%"],
        ["Expected loss if shipping treatment", f"{bayes.expected_loss_treatment*100:.4f} pp"],
        ["Expected loss if keeping control", f"{bayes.expected_loss_control*100:.4f} pp"],
        ["Control 95% credible interval",
         f"[{bayes.control_credible_interval[0]*100:.2f}%, {bayes.control_credible_interval[1]*100:.2f}%]"],
        ["Treatment 95% credible interval",
         f"[{bayes.treatment_credible_interval[0]*100:.2f}%, {bayes.treatment_credible_interval[1]*100:.2f}%]"],
    ]
    t = Table(bayes_rows, colWidths=[doc.width * 0.55, doc.width * 0.45])
    t.setStyle(table_style())
    story.append(t)
    story.append(Spacer(1, 3))
    story.append(Paragraph(f"Prior: Beta({bayes.prior_alpha:g}, {bayes.prior_beta:g})", small))

    # business impact
    story.append(Paragraph("Business impact", h2))
    story.append(Paragraph(_pdf_safe(
        f"Assumptions: {impact.daily_visitors:,} daily visitors, "
        f"{impact.traffic_split:.0%} of traffic affected, "
        f"${impact.revenue_per_conversion:,.2f} revenue per conversion."), small))
    story.append(Spacer(1, 3))
    impact_rows = [
        ["Metric", "Value"],
        ["Daily conversion lift", f"{impact.daily_conversion_lift:+.1f} conversions/day"],
        ["Daily revenue lift", f"${impact.daily_revenue_lift:+,.2f}/day"],
        ["Annual revenue lift (point estimate)", f"${impact.annual_revenue_lift:+,.0f}"],
        ["Annual range (treatment CI)",
         f"${impact.annual_revenue_lift_low:,.0f} to ${impact.annual_revenue_lift_high:,.0f}"],
        ["EV of shipping vs status quo", f"${rr.ev_ship_treatment:+,.2f}/day"],
    ]
    t = Table(impact_rows, colWidths=[doc.width * 0.55, doc.width * 0.45])
    t.setStyle(table_style())
    story.append(t)

    # scenarios
    story.append(Paragraph("Scenario analysis", h2))
    scen_rows = [list(scenarios.columns)] + scenarios.values.tolist()
    t = Table(scen_rows, colWidths=[doc.width * w for w in (0.20, 0.14, 0.20, 0.20, 0.12, 0.14)])
    t.setStyle(table_style())
    story.append(t)

    # caveats
    story.append(Paragraph("Caveats", h2))
    for c in [
        "Annualised figures extrapolate a short test window; seasonality and novelty effects may erode the lift.",
        "Revenue impact assumes the conversion lift is the only effect (no change in average order value).",
        "Scenario probabilities are illustrative weights, not posterior probabilities.",
    ]:
        story.append(Paragraph(f"&bull; {c}", small))

    doc.build(story, onFirstPage=_salmon_page, onLaterPages=_salmon_page)
    return buf.getvalue()